### ISSUE TITLE
Principio Open Close

### ISSUE THREAD

**Issue by JohannaLopez** [yvesmendes/sudoku-pure-java-implementation#3]
**Detalle:** En el código algunas clases utilizan score, dándole una responsabilidad mas a la clases
![image](https://user-images.githubusercontent.com/7936383/123180533-12eea000-d451-11eb-9d8e-b3f3de963d28.png)

mi propuesta es crear una clase para que se maneje el score, si llegara a darse el caso de un requerimiento , donde se necesita aumentar el score con bonos extras se podría trabajar sin afectar a otras clases.
![image](https://user-images.githubusercontent.com/7936383/123180662-4e896a00-d451-11eb-93bb-73e1cf5bdc63.png)
![image](https://user-images.githubusercontent.com/7936383/123180685-5b0dc280-d451-11eb-9e83-803558d34dc4.png)

**Comment by yvesmendes** [comment]
Aquí solo la clase Game interactúa directamente con el Score, por lo que entiendo que Score es parte de la clase Game. En el caso de la clase SudokuFacadeImpl, solo proporciona una abstracción para el front-end usando el design pattern facade (https://en.wikipedia.org/wiki/Facade_pattern) y en el caso de las clases Calculate *, usan el design pateen Strategy para permitir un cambio de cálculo respetando open/closed principle (https://pt.wikipedia.org/wiki/Strategy)
